package com.itheima.prize.commons.db.mapper;

import com.itheima.prize.commons.db.entity.ViewGameCurinfo;
import com.itheima.prize.commons.db.entity.ViewGameCurinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectKey;

public interface ViewGameCurinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_game_curinfo
     *
     * @mbg.generated
     */
    long countByExample(ViewGameCurinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_game_curinfo
     *
     * @mbg.generated
     */
    int deleteByExample(ViewGameCurinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_game_curinfo
     *
     * @mbg.generated
     */
    @Insert({
        "insert into view_game_curinfo (title, starttime, ",
        "endtime, type, ",
        "total, hit)",
        "values (#{title,jdbcType=VARCHAR}, #{starttime,jdbcType=TIMESTAMP}, ",
        "#{endtime,jdbcType=TIMESTAMP}, #{type,jdbcType=VARCHAR}, ",
        "#{total,jdbcType=DECIMAL}, #{hit,jdbcType=BIGINT})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(ViewGameCurinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_game_curinfo
     *
     * @mbg.generated
     */
    int insertSelective(ViewGameCurinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_game_curinfo
     *
     * @mbg.generated
     */
    List<ViewGameCurinfo> selectByExample(ViewGameCurinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_game_curinfo
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ViewGameCurinfo record, @Param("example") ViewGameCurinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_game_curinfo
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ViewGameCurinfo record, @Param("example") ViewGameCurinfoExample example);
}