package com.zcurd.account.model;

import com.zcurd.account.model.base.BaseCommonFile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CommonFile extends BaseCommonFile<CommonFile> {
	public static final CommonFile dao = new CommonFile().dao();
}
