package com.zcurd.account.model;

import com.zcurd.account.model.base.BaseZcurdField;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZcurdField extends BaseZcurdField<ZcurdField> {
	public static final ZcurdField dao = new ZcurdField().dao();
}
