package com.zcurd.account.model;

import com.zcurd.account.model.base.BaseZcurdHeadBtn;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZcurdHeadBtn extends BaseZcurdHeadBtn<ZcurdHeadBtn> {
	public static final ZcurdHeadBtn dao = new ZcurdHeadBtn().dao();
}
