package com.zcurd.account.model;

import com.zcurd.account.model.base.BaseZcurdHead;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZcurdHead extends BaseZcurdHead<ZcurdHead> {
	public static final ZcurdHead dao = new ZcurdHead().dao();
}
