package com.zcurd.account.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseZcurdHeadBtn<M extends BaseZcurdHeadBtn<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setHeadId(java.lang.Integer headId) {
		set("head_id", headId);
		return (M)this;
	}

	public java.lang.Integer getHeadId() {
		return get("head_id");
	}

	public M setBtnName(java.lang.String btnName) {
		set("btn_name", btnName);
		return (M)this;
	}

	public java.lang.String getBtnName() {
		return get("btn_name");
	}

	public M setBtnIcon(java.lang.String btnIcon) {
		set("btn_icon", btnIcon);
		return (M)this;
	}

	public java.lang.String getBtnIcon() {
		return get("btn_icon");
	}

	public M setLocation(java.lang.Integer location) {
		set("location", location);
		return (M)this;
	}

	public java.lang.Integer getLocation() {
		return get("location");
	}

	public M setAction(java.lang.Integer action) {
		set("action", action);
		return (M)this;
	}

	public java.lang.Integer getAction() {
		return get("action");
	}

	public M setFuncContent(java.lang.String funcContent) {
		set("func_content", funcContent);
		return (M)this;
	}

	public java.lang.String getFuncContent() {
		return get("func_content");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
