package com.zcurd.account.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseZcurdHead<M extends BaseZcurdHead<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public M setTableName(java.lang.String tableName) {
		set("table_name", tableName);
		return (M)this;
	}

	public java.lang.String getTableName() {
		return get("table_name");
	}

	public M setFormName(java.lang.String formName) {
		set("form_name", formName);
		return (M)this;
	}

	public java.lang.String getFormName() {
		return get("form_name");
	}

	public M setIdField(java.lang.String idField) {
		set("id_field", idField);
		return (M)this;
	}

	public java.lang.String getIdField() {
		return get("id_field");
	}

	public M setIsAuto(java.lang.Integer isAuto) {
		set("is_auto", isAuto);
		return (M)this;
	}

	public java.lang.Integer getIsAuto() {
		return get("is_auto");
	}

	public M setFormType(java.lang.Integer formType) {
		set("form_type", formType);
		return (M)this;
	}

	public java.lang.Integer getFormType() {
		return get("form_type");
	}

	public M setDialogSize(java.lang.String dialogSize) {
		set("dialog_size", dialogSize);
		return (M)this;
	}

	public java.lang.String getDialogSize() {
		return get("dialog_size");
	}

	public M setDbSource(java.lang.String dbSource) {
		set("db_source", dbSource);
		return (M)this;
	}

	public java.lang.String getDbSource() {
		return get("db_source");
	}

	public M setHandleClass(java.lang.String handleClass) {
		set("handle_class", handleClass);
		return (M)this;
	}

	public java.lang.String getHandleClass() {
		return get("handle_class");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
