package com.itheima.prize.commons.db.entity;

import java.io.Serializable;
import java.util.Date;

public class TaskBase implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_base.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_base.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_base.target_type
     *
     * @mbg.generated
     */
    private Integer targetType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_base.cron
     *
     * @mbg.generated
     */
    private String cron;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_base.last_run_result
     *
     * @mbg.generated
     */
    private String lastRunResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_base.last_run_time
     *
     * @mbg.generated
     */
    private Date lastRunTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_base.last_run_time_cost
     *
     * @mbg.generated
     */
    private Integer lastRunTimeCost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_base.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_base.create_user_id
     *
     * @mbg.generated
     */
    private Integer createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_base.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_base.target_value
     *
     * @mbg.generated
     */
    private String targetValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table task_base
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_base.id
     *
     * @return the value of task_base.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_base.id
     *
     * @param id the value for task_base.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_base.name
     *
     * @return the value of task_base.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_base.name
     *
     * @param name the value for task_base.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_base.target_type
     *
     * @return the value of task_base.target_type
     *
     * @mbg.generated
     */
    public Integer getTargetType() {
        return targetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_base.target_type
     *
     * @param targetType the value for task_base.target_type
     *
     * @mbg.generated
     */
    public void setTargetType(Integer targetType) {
        this.targetType = targetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_base.cron
     *
     * @return the value of task_base.cron
     *
     * @mbg.generated
     */
    public String getCron() {
        return cron;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_base.cron
     *
     * @param cron the value for task_base.cron
     *
     * @mbg.generated
     */
    public void setCron(String cron) {
        this.cron = cron == null ? null : cron.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_base.last_run_result
     *
     * @return the value of task_base.last_run_result
     *
     * @mbg.generated
     */
    public String getLastRunResult() {
        return lastRunResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_base.last_run_result
     *
     * @param lastRunResult the value for task_base.last_run_result
     *
     * @mbg.generated
     */
    public void setLastRunResult(String lastRunResult) {
        this.lastRunResult = lastRunResult == null ? null : lastRunResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_base.last_run_time
     *
     * @return the value of task_base.last_run_time
     *
     * @mbg.generated
     */
    public Date getLastRunTime() {
        return lastRunTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_base.last_run_time
     *
     * @param lastRunTime the value for task_base.last_run_time
     *
     * @mbg.generated
     */
    public void setLastRunTime(Date lastRunTime) {
        this.lastRunTime = lastRunTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_base.last_run_time_cost
     *
     * @return the value of task_base.last_run_time_cost
     *
     * @mbg.generated
     */
    public Integer getLastRunTimeCost() {
        return lastRunTimeCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_base.last_run_time_cost
     *
     * @param lastRunTimeCost the value for task_base.last_run_time_cost
     *
     * @mbg.generated
     */
    public void setLastRunTimeCost(Integer lastRunTimeCost) {
        this.lastRunTimeCost = lastRunTimeCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_base.status
     *
     * @return the value of task_base.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_base.status
     *
     * @param status the value for task_base.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_base.create_user_id
     *
     * @return the value of task_base.create_user_id
     *
     * @mbg.generated
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_base.create_user_id
     *
     * @param createUserId the value for task_base.create_user_id
     *
     * @mbg.generated
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_base.create_time
     *
     * @return the value of task_base.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_base.create_time
     *
     * @param createTime the value for task_base.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_base.target_value
     *
     * @return the value of task_base.target_value
     *
     * @mbg.generated
     */
    public String getTargetValue() {
        return targetValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_base.target_value
     *
     * @param targetValue the value for task_base.target_value
     *
     * @mbg.generated
     */
    public void setTargetValue(String targetValue) {
        this.targetValue = targetValue == null ? null : targetValue.trim();
    }
}