package com.itheima.prize.commons.db.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class ViewGameProductnum implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_game_productnum.gameid
     *
     * @mbg.generated
     */
    private Integer gameid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_game_productnum.num
     *
     * @mbg.generated
     */
    private BigDecimal num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table view_game_productnum
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_game_productnum.gameid
     *
     * @return the value of view_game_productnum.gameid
     *
     * @mbg.generated
     */
    public Integer getGameid() {
        return gameid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_game_productnum.gameid
     *
     * @param gameid the value for view_game_productnum.gameid
     *
     * @mbg.generated
     */
    public void setGameid(Integer gameid) {
        this.gameid = gameid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_game_productnum.num
     *
     * @return the value of view_game_productnum.num
     *
     * @mbg.generated
     */
    public BigDecimal getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_game_productnum.num
     *
     * @param num the value for view_game_productnum.num
     *
     * @mbg.generated
     */
    public void setNum(BigDecimal num) {
        this.num = num;
    }
}