package com.itheima.prize.commons.db.entity;

import java.io.Serializable;

public class ViewGameHitnum implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_game_hitnum.gameid
     *
     * @mbg.generated
     */
    private Integer gameid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_game_hitnum.num
     *
     * @mbg.generated
     */
    private Long num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table view_game_hitnum
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_game_hitnum.gameid
     *
     * @return the value of view_game_hitnum.gameid
     *
     * @mbg.generated
     */
    public Integer getGameid() {
        return gameid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_game_hitnum.gameid
     *
     * @param gameid the value for view_game_hitnum.gameid
     *
     * @mbg.generated
     */
    public void setGameid(Integer gameid) {
        this.gameid = gameid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_game_hitnum.num
     *
     * @return the value of view_game_hitnum.num
     *
     * @mbg.generated
     */
    public Long getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_game_hitnum.num
     *
     * @param num the value for view_game_hitnum.num
     *
     * @mbg.generated
     */
    public void setNum(Long num) {
        this.num = num;
    }
}