package com.itheima.prize.commons.db.entity;

import java.io.Serializable;
import java.util.Date;

public class ZcurdHeadJs implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcurd_head_js.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcurd_head_js.head_id
     *
     * @mbg.generated
     */
    private Integer headId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcurd_head_js.page
     *
     * @mbg.generated
     */
    private String page;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcurd_head_js.sql_content
     *
     * @mbg.generated
     */
    private String sqlContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcurd_head_js.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcurd_head_js.js_content
     *
     * @mbg.generated
     */
    private String jsContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zcurd_head_js
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcurd_head_js.id
     *
     * @return the value of zcurd_head_js.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcurd_head_js.id
     *
     * @param id the value for zcurd_head_js.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcurd_head_js.head_id
     *
     * @return the value of zcurd_head_js.head_id
     *
     * @mbg.generated
     */
    public Integer getHeadId() {
        return headId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcurd_head_js.head_id
     *
     * @param headId the value for zcurd_head_js.head_id
     *
     * @mbg.generated
     */
    public void setHeadId(Integer headId) {
        this.headId = headId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcurd_head_js.page
     *
     * @return the value of zcurd_head_js.page
     *
     * @mbg.generated
     */
    public String getPage() {
        return page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcurd_head_js.page
     *
     * @param page the value for zcurd_head_js.page
     *
     * @mbg.generated
     */
    public void setPage(String page) {
        this.page = page == null ? null : page.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcurd_head_js.sql_content
     *
     * @return the value of zcurd_head_js.sql_content
     *
     * @mbg.generated
     */
    public String getSqlContent() {
        return sqlContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcurd_head_js.sql_content
     *
     * @param sqlContent the value for zcurd_head_js.sql_content
     *
     * @mbg.generated
     */
    public void setSqlContent(String sqlContent) {
        this.sqlContent = sqlContent == null ? null : sqlContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcurd_head_js.create_time
     *
     * @return the value of zcurd_head_js.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcurd_head_js.create_time
     *
     * @param createTime the value for zcurd_head_js.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcurd_head_js.js_content
     *
     * @return the value of zcurd_head_js.js_content
     *
     * @mbg.generated
     */
    public String getJsContent() {
        return jsContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcurd_head_js.js_content
     *
     * @param jsContent the value for zcurd_head_js.js_content
     *
     * @mbg.generated
     */
    public void setJsContent(String jsContent) {
        this.jsContent = jsContent == null ? null : jsContent.trim();
    }
}